import Flare.L3_Protocol.H2

-- Frame codec
#print axioms Flare.L3.H2.parse_encode
#print axioms Flare.L3.H2.parse_short
#print axioms Flare.L3.H2.parse_never_raises
#print axioms Flare.L3.H2.parse_consumed
#print axioms Flare.L3.H2.precheck_bounds
-- HPACK dynamic table, synchronisation, decoder
#print axioms Flare.L3.H2.Hpack.evict_spec
#print axioms Flare.L3.H2.Hpack.insert_spec
#print axioms Flare.L3.H2.Hpack.lookup_spec
#print axioms Flare.L3.H2.Hpack.inv_insert
#print axioms Flare.L3.H2.Hpack.inv_sizeUpdate
#print axioms Flare.L3.H2.Hpack.utf8Lossy_length_ge
#print axioms Flare.L3.H2.Hpack.prefix_inv
#print axioms Flare.L3.H2.Hpack.prefix_inv_flare
#print axioms Flare.L3.H2.Hpack.lookup_sound
#print axioms Flare.L3.H2.Hpack.sync_exact
#print axioms Flare.L3.H2.Hpack.decode_budget_impl
#print axioms Flare.L3.H2.Hpack.decode_budget_fixed
#print axioms Flare.L3.H2.Hpack.decode_table_inv
#print axioms Flare.L3.H2.Hpack.decode_encode
-- Request header validation
#print axioms Flare.L3.H2.Validate.loop_iff
#print axioms Flare.L3.H2.Validate.fold_facts
#print axioms Flare.L3.H2.Validate.fixedNameOK_iff
#print axioms Flare.L3.H2.Validate.implNameOK_spec
-- Connection state machine: invariants, flow control, per-clause theorems
#print axioms Flare.L3.H2.Conn.win_reachable
#print axioms Flare.L3.H2.Conn.run_live
#print axioms Flare.L3.H2.Conn.h2_01_fixed
#print axioms Flare.L3.H2.Conn.h2_09_fixed
#print axioms Flare.L3.H2.Conn.handle_headers0
#print axioms Flare.L3.H2.Conn.handle_goaway_short
#print axioms Flare.L3.H2.Conn.handle_reuse
#print axioms Flare.L3.H2.Conn.handle_client_unopened
#print axioms Flare.L3.H2.Conn.drive_first_not_settings
#print axioms Flare.L3.H2.Conn.handle_client_late_wu
#print axioms Flare.L3.H2.Conn.handle_client_late_rst
#print axioms Flare.L3.H2.Conn.refuse_at_limit
-- Connection sequencing (CONTINUATION, GOAWAY) and HPACK composition on the real codec
#print axioms Flare.L3.H2.Conn.seq_step
#print axioms Flare.L3.H2.Conn.seq_run
#print axioms Flare.L3.H2.Conn.hb_local
#print axioms Flare.L3.H2.Hpack.pinv_init
#print axioms Flare.L3.H2.Hpack.decodeOne_rep
#print axioms Flare.L3.H2.Hpack.decode_block
#print axioms Flare.L3.H2.Hpack.real_correct
#print axioms Flare.L3.H2.Hpack.real_huff
#print axioms Flare.L3.H2.Conn.decFold_blocks
#print axioms Flare.L3.H2.Conn.seq_runD
#print axioms Flare.L3.H2.Conn.lookup_sound_conn
-- RFC 9113 §5.1: spec LTS, refinement of the fixed model, shipped-code classification
#print axioms Flare.L3.H2.StreamSpec.closed_no_send_wu
#print axioms Flare.L3.H2.Refine.fixed_frame
#print axioms Flare.L3.H2.Refine.fixed_local
#print axioms Flare.L3.H2.Refine.fixed_step
#print axioms Flare.L3.H2.Refine.fixed_run
#print axioms Flare.L3.H2.Refine.fixed_refines
#print axioms Flare.L3.H2.Refine.shipped_eq_fixed
#print axioms Flare.L3.H2.Refine.shipped_classified
#print axioms Flare.L3.H2.Refine.shipped_run
-- Client streaming-body mode
#print axioms Flare.L3.H2.Streaming.step_rel
#print axioms Flare.L3.H2.Streaming.ti_step
#print axioms Flare.L3.H2.Streaming.ti_run
#print axioms Flare.L3.H2.Streaming.pending_le
#print axioms Flare.L3.H2.Streaming.fifo_run
#print axioms Flare.L3.H2.Streaming.data_credit
#print axioms Flare.L3.H2.Streaming.drain_credit
-- Counterexamples and fixes
#print axioms Flare.Bugs.H2_01.counterexample
#print axioms Flare.Bugs.H2_01.fixed
#print axioms Flare.Bugs.H2_02.counterexample
#print axioms Flare.Bugs.H2_02.fixed
#print axioms Flare.Bugs.H2_03.counterexample
#print axioms Flare.Bugs.H2_03.fixed
#print axioms Flare.Bugs.H2_04.counterexample
#print axioms Flare.Bugs.H2_04.fixed
#print axioms Flare.Bugs.H2_05.counterexample
#print axioms Flare.Bugs.H2_05.counterexample_dup
#print axioms Flare.Bugs.H2_05.fixed
#print axioms Flare.Bugs.H2_05.fixed_complete
#print axioms Flare.Bugs.H2_06.counterexample
#print axioms Flare.Bugs.H2_06.fixed
#print axioms Flare.Bugs.H2_07.counterexample
#print axioms Flare.Bugs.H2_07.fixed
#print axioms Flare.Bugs.H2_08.counterexample
#print axioms Flare.Bugs.H2_08.fixed
#print axioms Flare.Bugs.H2_09.counterexample
#print axioms Flare.Bugs.H2_09.fixed
#print axioms Flare.Bugs.H2_10.counterexample
#print axioms Flare.Bugs.H2_10.counterexample_request
#print axioms Flare.Bugs.H2_10.fixed
#print axioms Flare.Bugs.H2_11.counterexample
#print axioms Flare.Bugs.H2_11.fixed
#print axioms Flare.Bugs.HPACK_01.counterexample
#print axioms Flare.Bugs.HPACK_01.fixed
#print axioms Flare.Bugs.HPACK_02.counterexample
#print axioms Flare.Bugs.HPACK_02.fixed
#print axioms Flare.Bugs.HPACK_03.counterexample
#print axioms Flare.Bugs.HPACK_03.fixed
#print axioms Flare.Bugs.HPACK_01.bug_real
#print axioms Flare.Bugs.HPACK_02.bug_real
#print axioms Flare.Bugs.HPACK_02.fixed_trace_real
#print axioms Flare.Bugs.HPACK_03.bug_real
#print axioms Flare.Bugs.HPACK_03.fixed_trace_real
#print axioms Flare.Bugs.H2_12.counterexample
#print axioms Flare.Bugs.H2_12.fixed
#print axioms Flare.Bugs.H2_13.counterexample
#print axioms Flare.Bugs.H2_13.fixed
#print axioms Flare.Bugs.H2_14.counterexample
#print axioms Flare.Bugs.H2_14.fixed
#print axioms Flare.Bugs.H2_15.counterexample
#print axioms Flare.Bugs.H2_15.fixed
#print axioms Flare.Bugs.H2_15.fixed_rst
#print axioms Flare.Bugs.H2_16.counterexample
#print axioms Flare.Bugs.H2_16.fixed
#print axioms Flare.Bugs.H2_16.fixed_wu
#print axioms Flare.Bugs.H2_17.counterexample
#print axioms Flare.Bugs.H2_17.fixed
#print axioms Flare.Bugs.H2_18.bug
#print axioms Flare.Bugs.H2_18.fixed
#print axioms Flare.Bugs.H2_18.shipped_raises
#print axioms Flare.Bugs.H2_19.counterexample
#print axioms Flare.Bugs.H2_19.fixed
#print axioms Flare.Bugs.H2_20.counterexample
#print axioms Flare.Bugs.H2_20.fixed
-- Departure witnesses of the shipped code from §5.1 (one per guard)
#print axioms Flare.Bugs.H2_Refine.w02
#print axioms Flare.Bugs.H2_Refine.w03
#print axioms Flare.Bugs.H2_Refine.w04
#print axioms Flare.Bugs.H2_Refine.w06
#print axioms Flare.Bugs.H2_Refine.w08
#print axioms Flare.Bugs.H2_Refine.w11
#print axioms Flare.Bugs.H2_Refine.w14
#print axioms Flare.Bugs.H2_Refine.w15
#print axioms Flare.Bugs.H2_Refine.w16
#print axioms Flare.Bugs.H2_Refine.w17
#print axioms Flare.Bugs.H2_Refine.w18
#print axioms Flare.Bugs.H2_Refine.w19
#print axioms Flare.Bugs.H2_Refine.w20
#print axioms Flare.Bugs.H2_Refine.w12_departs
#print axioms Flare.Bugs.H2_Refine.w13_departs
