"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of ``tests/qpack/`` into one compiled
binary so the 2 separate compiler invocations become one. Run it with
``mojo -I . -I tests/qpack`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_qpack import (
    test_static_table_size as test_qpack__test_static_table_size,
)
from test_qpack import (
    test_static_table_lookup_known_indices as test_qpack__test_static_table_lookup_known_indices,
)
from test_qpack import (
    test_static_table_lookup_out_of_range as test_qpack__test_static_table_lookup_out_of_range,
)
from test_qpack import (
    test_static_table_find_full_match as test_qpack__test_static_table_find_full_match,
)
from test_qpack import (
    test_static_table_find_name_only as test_qpack__test_static_table_find_name_only,
)
from test_qpack import (
    test_round_trip_full_static_match as test_qpack__test_round_trip_full_static_match,
)
from test_qpack import (
    test_round_trip_literal_with_name_reference as test_qpack__test_round_trip_literal_with_name_reference,
)
from test_qpack import (
    test_round_trip_literal_with_literal_name as test_qpack__test_round_trip_literal_with_literal_name,
)
from test_qpack import (
    test_round_trip_mixed_field_lines as test_qpack__test_round_trip_mixed_field_lines,
)
from test_qpack import (
    test_decode_rejects_indexed_dynamic as test_qpack__test_decode_rejects_indexed_dynamic,
)
from test_qpack import (
    test_decode_rejects_literal_with_dynamic_name_ref as test_qpack__test_decode_rejects_literal_with_dynamic_name_ref,
)
from test_qpack import (
    test_decode_rejects_required_insert_count_above_zero as test_qpack__test_decode_rejects_required_insert_count_above_zero,
)
from test_qpack import (
    test_round_trip_long_value_uses_huffman_when_shorter as test_qpack__test_round_trip_long_value_uses_huffman_when_shorter,
)
from test_qpack import (
    test_raw_literal_value_that_is_not_utf8_is_refused as test_qpack__test_raw_literal_value_that_is_not_utf8_is_refused,
)
from test_qpack import (
    test_huffman_literal_value_that_is_not_utf8_is_refused as test_qpack__test_huffman_literal_value_that_is_not_utf8_is_refused,
)
from test_qpack import (
    test_literal_name_that_is_not_utf8_is_refused as test_qpack__test_literal_name_that_is_not_utf8_is_refused,
)
from test_qpack import (
    test_valid_utf8_literal_value_is_still_accepted as test_qpack__test_valid_utf8_literal_value_is_still_accepted,
)
from test_qpack_dynamic import (
    test_entry_size as test_qpack_dynamic__test_entry_size,
)
from test_qpack_dynamic import (
    test_table_insert_and_index as test_qpack_dynamic__test_table_insert_and_index,
)
from test_qpack_dynamic import (
    test_table_eviction as test_qpack_dynamic__test_table_eviction,
)
from test_qpack_dynamic import (
    test_insert_too_big_fails as test_qpack_dynamic__test_insert_too_big_fails,
)
from test_qpack_dynamic import (
    test_required_insert_count_roundtrip as test_qpack_dynamic__test_required_insert_count_roundtrip,
)
from test_qpack_dynamic import (
    test_apply_encoder_instructions_literal as test_qpack_dynamic__test_apply_encoder_instructions_literal,
)
from test_qpack_dynamic import (
    test_apply_encoder_instructions_name_ref_and_dup as test_qpack_dynamic__test_apply_encoder_instructions_name_ref_and_dup,
)
from test_qpack_dynamic import (
    test_decoder_stream_instructions as test_qpack_dynamic__test_decoder_stream_instructions,
)
from test_qpack_dynamic import (
    test_field_section_dynamic_roundtrip as test_qpack_dynamic__test_field_section_dynamic_roundtrip,
)
from test_qpack_dynamic import (
    test_blocked_section_raises as test_qpack_dynamic__test_blocked_section_raises,
)
from test_qpack_dynamic import (
    test_encoder_references_no_unacknowledged_entry as test_qpack_dynamic__test_encoder_references_no_unacknowledged_entry,
)
from test_qpack_dynamic import (
    test_encoder_refuses_an_insert_that_would_evict as test_qpack_dynamic__test_encoder_refuses_an_insert_that_would_evict,
)
from test_qpack_dynamic import (
    test_capacity_above_the_advertised_limit_is_refused as test_qpack_dynamic__test_capacity_above_the_advertised_limit_is_refused,
)
from test_qpack_dynamic import (
    test_non_utf8_literal_on_the_encoder_stream_is_an_error as test_qpack_dynamic__test_non_utf8_literal_on_the_encoder_stream_is_an_error,
)
from test_qpack_dynamic import (
    test_name_ref_into_an_empty_table_is_an_encoder_stream_error as test_qpack_dynamic__test_name_ref_into_an_empty_table_is_an_encoder_stream_error,
)
from test_qpack_dynamic import (
    test_name_ref_past_the_live_entries_is_an_encoder_stream_error as test_qpack_dynamic__test_name_ref_past_the_live_entries_is_an_encoder_stream_error,
)
from test_qpack_dynamic import (
    test_duplicate_of_a_missing_entry_is_an_encoder_stream_error as test_qpack_dynamic__test_duplicate_of_a_missing_entry_is_an_encoder_stream_error,
)
from test_qpack_dynamic import (
    test_truncated_valid_name_ref_still_waits_for_more_bytes as test_qpack_dynamic__test_truncated_valid_name_ref_still_waits_for_more_bytes,
)
from test_qpack_dynamic import (
    test_ric_zero_section_cannot_read_the_dynamic_table as test_qpack_dynamic__test_ric_zero_section_cannot_read_the_dynamic_table,
)
from test_qpack_dynamic import (
    test_sign_set_with_delta_base_not_below_ric_is_refused as test_qpack_dynamic__test_sign_set_with_delta_base_not_below_ric_is_refused,
)
from test_qpack_dynamic import (
    test_post_base_reference_at_or_above_ric_is_refused as test_qpack_dynamic__test_post_base_reference_at_or_above_ric_is_refused,
)
from test_qpack_dynamic import (
    test_pre_base_relative_index_beyond_base_is_refused as test_qpack_dynamic__test_pre_base_relative_index_beyond_base_is_refused,
)
from test_qpack_dynamic import (
    test_truncated_prefix_without_sign_byte_is_refused as test_qpack_dynamic__test_truncated_prefix_without_sign_byte_is_refused,
)


def main() raises:
    var suite = TestSuite()
    # tests/qpack/test_qpack.mojo
    suite.test[test_qpack__test_static_table_size]()
    suite.test[test_qpack__test_static_table_lookup_known_indices]()
    suite.test[test_qpack__test_static_table_lookup_out_of_range]()
    suite.test[test_qpack__test_static_table_find_full_match]()
    suite.test[test_qpack__test_static_table_find_name_only]()
    suite.test[test_qpack__test_round_trip_full_static_match]()
    suite.test[test_qpack__test_round_trip_literal_with_name_reference]()
    suite.test[test_qpack__test_round_trip_literal_with_literal_name]()
    suite.test[test_qpack__test_round_trip_mixed_field_lines]()
    suite.test[test_qpack__test_decode_rejects_indexed_dynamic]()
    suite.test[test_qpack__test_decode_rejects_literal_with_dynamic_name_ref]()
    suite.test[
        test_qpack__test_decode_rejects_required_insert_count_above_zero
    ]()
    suite.test[
        test_qpack__test_round_trip_long_value_uses_huffman_when_shorter
    ]()
    suite.test[test_qpack__test_raw_literal_value_that_is_not_utf8_is_refused]()
    suite.test[
        test_qpack__test_huffman_literal_value_that_is_not_utf8_is_refused
    ]()
    suite.test[test_qpack__test_literal_name_that_is_not_utf8_is_refused]()
    suite.test[test_qpack__test_valid_utf8_literal_value_is_still_accepted]()
    # tests/qpack/test_qpack_dynamic.mojo
    suite.test[test_qpack_dynamic__test_entry_size]()
    suite.test[test_qpack_dynamic__test_table_insert_and_index]()
    suite.test[test_qpack_dynamic__test_table_eviction]()
    suite.test[test_qpack_dynamic__test_insert_too_big_fails]()
    suite.test[test_qpack_dynamic__test_required_insert_count_roundtrip]()
    suite.test[test_qpack_dynamic__test_apply_encoder_instructions_literal]()
    suite.test[
        test_qpack_dynamic__test_apply_encoder_instructions_name_ref_and_dup
    ]()
    suite.test[test_qpack_dynamic__test_decoder_stream_instructions]()
    suite.test[test_qpack_dynamic__test_field_section_dynamic_roundtrip]()
    suite.test[test_qpack_dynamic__test_blocked_section_raises]()
    suite.test[
        test_qpack_dynamic__test_encoder_references_no_unacknowledged_entry
    ]()
    suite.test[
        test_qpack_dynamic__test_encoder_refuses_an_insert_that_would_evict
    ]()
    suite.test[
        test_qpack_dynamic__test_capacity_above_the_advertised_limit_is_refused
    ]()
    suite.test[
        test_qpack_dynamic__test_non_utf8_literal_on_the_encoder_stream_is_an_error
    ]()
    suite.test[
        test_qpack_dynamic__test_name_ref_into_an_empty_table_is_an_encoder_stream_error
    ]()
    suite.test[
        test_qpack_dynamic__test_name_ref_past_the_live_entries_is_an_encoder_stream_error
    ]()
    suite.test[
        test_qpack_dynamic__test_duplicate_of_a_missing_entry_is_an_encoder_stream_error
    ]()
    suite.test[
        test_qpack_dynamic__test_truncated_valid_name_ref_still_waits_for_more_bytes
    ]()
    suite.test[
        test_qpack_dynamic__test_ric_zero_section_cannot_read_the_dynamic_table
    ]()
    suite.test[
        test_qpack_dynamic__test_sign_set_with_delta_base_not_below_ric_is_refused
    ]()
    suite.test[
        test_qpack_dynamic__test_post_base_reference_at_or_above_ric_is_refused
    ]()
    suite.test[
        test_qpack_dynamic__test_pre_base_relative_index_beyond_base_is_refused
    ]()
    suite.test[
        test_qpack_dynamic__test_truncated_prefix_without_sign_byte_is_refused
    ]()
    suite^.run()
