"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of ``tests/dns/`` into one compiled
binary so the 3 separate compiler invocations become one. Run it with
``mojo -I . -I tests/dns`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_async_resolve import (
    test_resolve_async_matches_sync_localhost as test_async_resolve__test_resolve_async_matches_sync_localhost,
)
from test_async_resolve import (
    test_resolve_async_empty_host_raises as test_async_resolve__test_resolve_async_empty_host_raises,
)
from test_async_resolve import (
    test_resolve_async_preflipped_cancel_raises as test_async_resolve__test_resolve_async_preflipped_cancel_raises,
)
from test_async_resolve import (
    test_happy_eyeballs_interleaves_families as test_async_resolve__test_happy_eyeballs_interleaves_families,
)
from test_async_resolve import (
    test_happy_eyeballs_uneven_families as test_async_resolve__test_happy_eyeballs_uneven_families,
)
from test_async_resolve import (
    test_happy_eyeballs_keeps_preferred_ipv4_first as test_async_resolve__test_happy_eyeballs_keeps_preferred_ipv4_first,
)
from test_async_resolve import (
    test_happy_eyeballs_ipv4_first_alternates_and_keeps_family_order as test_async_resolve__test_happy_eyeballs_ipv4_first_alternates_and_keeps_family_order,
)
from test_async_resolve import (
    test_happy_eyeballs_empty_and_single as test_async_resolve__test_happy_eyeballs_empty_and_single,
)
from test_async_resolve import (
    test_cache_async_serves_hit_without_spawn as test_async_resolve__test_cache_async_serves_hit_without_spawn,
)
from test_dns import (
    test_resolve_localhost_non_empty as test_dns__test_resolve_localhost_non_empty,
)
from test_dns import (
    test_resolve_localhost_has_loopback as test_dns__test_resolve_localhost_has_loopback,
)
from test_dns import (
    test_resolve_v4_localhost_non_empty as test_dns__test_resolve_v4_localhost_non_empty,
)
from test_dns import (
    test_resolve_v4_all_ipv4 as test_dns__test_resolve_v4_all_ipv4,
)
from test_dns import (
    test_resolve_v4_contains_127 as test_dns__test_resolve_v4_contains_127,
)
from test_dns import (
    test_resolve_numeric_ipv4_passthrough as test_dns__test_resolve_numeric_ipv4_passthrough,
)
from test_dns import (
    test_resolve_numeric_ipv6_passthrough as test_dns__test_resolve_numeric_ipv6_passthrough,
)
from test_dns import (
    test_resolve_numeric_v4_192 as test_dns__test_resolve_numeric_v4_192,
)
from test_dns import (
    test_resolve_v6_localhost_includes_v6_or_raises as test_dns__test_resolve_v6_localhost_includes_v6_or_raises,
)
from test_dns import (
    test_resolve_fqdn_trailing_dot as test_dns__test_resolve_fqdn_trailing_dot,
)
from test_dns import (
    test_resolve_empty_host_raises as test_dns__test_resolve_empty_host_raises,
)
from test_dns import (
    test_resolve_nonexistent_raises as test_dns__test_resolve_nonexistent_raises,
)
from test_dns import (
    test_resolve_null_byte_injection_raises as test_dns__test_resolve_null_byte_injection_raises,
)
from test_dns import (
    test_resolve_crlf_injection_raises as test_dns__test_resolve_crlf_injection_raises,
)
from test_dns import (
    test_resolve_at_sign_raises as test_dns__test_resolve_at_sign_raises,
)
from test_dns import (
    test_resolve_hostname_too_long_raises as test_dns__test_resolve_hostname_too_long_raises,
)
from test_dns import (
    test_resolve_accepts_253_byte_name as test_dns__test_resolve_accepts_253_byte_name,
)
from test_dns import (
    test_resolve_accepts_253_byte_absolute_name as test_dns__test_resolve_accepts_253_byte_absolute_name,
)
from test_dns import (
    test_resolve_rejects_254_byte_name_without_root_dot as test_dns__test_resolve_rejects_254_byte_name_without_root_dot,
)
from test_dns import (
    test_too_long_message_does_not_split_a_two_byte_char as test_dns__test_too_long_message_does_not_split_a_two_byte_char,
)
from test_dns import (
    test_too_long_message_does_not_split_a_four_byte_char as test_dns__test_too_long_message_does_not_split_a_four_byte_char,
)
from test_dns import (
    test_too_long_message_keeps_a_char_that_ends_at_byte_20 as test_dns__test_too_long_message_keeps_a_char_that_ends_at_byte_20,
)
from test_dns import (
    test_too_long_message_quotes_20_ascii_bytes as test_dns__test_too_long_message_quotes_20_ascii_bytes,
)
from test_dns import (
    test_resolve_label_too_long_raises as test_dns__test_resolve_label_too_long_raises,
)
from test_dns_cache import (
    test_within_ttl_no_second_syscall as test_dns_cache__test_within_ttl_no_second_syscall,
)
from test_dns_cache import (
    test_zero_ttl_always_resolves as test_dns_cache__test_zero_ttl_always_resolves,
)
from test_dns_cache import (
    test_distinct_hosts_each_resolve as test_dns_cache__test_distinct_hosts_each_resolve,
)
from test_dns_cache import (
    test_invalidate_forces_resolve as test_dns_cache__test_invalidate_forces_resolve,
)
from test_dns_cache import (
    test_clear_drops_all as test_dns_cache__test_clear_drops_all,
)
from test_dns_cache import (
    test_names_match_case_insensitively as test_dns_cache__test_names_match_case_insensitively,
)
from test_dns_cache import (
    test_cache_is_bounded as test_dns_cache__test_cache_is_bounded,
)
from test_dns_cache import (
    test_int_max_ttl_means_cache_forever as test_dns_cache__test_int_max_ttl_means_cache_forever,
)
from test_dns_cache import (
    test_ttl_that_overflows_the_expiry_still_caches as test_dns_cache__test_ttl_that_overflows_the_expiry_still_caches,
)
from test_dns_cache import (
    test_saturated_expiries_are_still_evicted as test_dns_cache__test_saturated_expiries_are_still_evicted,
)


def main() raises:
    var suite = TestSuite()
    # tests/dns/test_async_resolve.mojo
    suite.test[test_async_resolve__test_resolve_async_matches_sync_localhost]()
    suite.test[test_async_resolve__test_resolve_async_empty_host_raises]()
    suite.test[
        test_async_resolve__test_resolve_async_preflipped_cancel_raises
    ]()
    suite.test[test_async_resolve__test_happy_eyeballs_interleaves_families]()
    suite.test[test_async_resolve__test_happy_eyeballs_uneven_families]()
    suite.test[
        test_async_resolve__test_happy_eyeballs_keeps_preferred_ipv4_first
    ]()
    suite.test[
        test_async_resolve__test_happy_eyeballs_ipv4_first_alternates_and_keeps_family_order
    ]()
    suite.test[test_async_resolve__test_happy_eyeballs_empty_and_single]()
    suite.test[test_async_resolve__test_cache_async_serves_hit_without_spawn]()
    # tests/dns/test_dns.mojo
    suite.test[test_dns__test_resolve_localhost_non_empty]()
    suite.test[test_dns__test_resolve_localhost_has_loopback]()
    suite.test[test_dns__test_resolve_v4_localhost_non_empty]()
    suite.test[test_dns__test_resolve_v4_all_ipv4]()
    suite.test[test_dns__test_resolve_v4_contains_127]()
    suite.test[test_dns__test_resolve_numeric_ipv4_passthrough]()
    suite.test[test_dns__test_resolve_numeric_ipv6_passthrough]()
    suite.test[test_dns__test_resolve_numeric_v4_192]()
    suite.test[test_dns__test_resolve_v6_localhost_includes_v6_or_raises]()
    suite.test[test_dns__test_resolve_fqdn_trailing_dot]()
    suite.test[test_dns__test_resolve_empty_host_raises]()
    suite.test[test_dns__test_resolve_nonexistent_raises]()
    suite.test[test_dns__test_resolve_null_byte_injection_raises]()
    suite.test[test_dns__test_resolve_crlf_injection_raises]()
    suite.test[test_dns__test_resolve_at_sign_raises]()
    suite.test[test_dns__test_resolve_hostname_too_long_raises]()
    suite.test[test_dns__test_resolve_accepts_253_byte_name]()
    suite.test[test_dns__test_resolve_accepts_253_byte_absolute_name]()
    suite.test[test_dns__test_resolve_rejects_254_byte_name_without_root_dot]()
    suite.test[test_dns__test_too_long_message_does_not_split_a_two_byte_char]()
    suite.test[
        test_dns__test_too_long_message_does_not_split_a_four_byte_char
    ]()
    suite.test[
        test_dns__test_too_long_message_keeps_a_char_that_ends_at_byte_20
    ]()
    suite.test[test_dns__test_too_long_message_quotes_20_ascii_bytes]()
    suite.test[test_dns__test_resolve_label_too_long_raises]()
    # tests/dns/test_dns_cache.mojo
    suite.test[test_dns_cache__test_within_ttl_no_second_syscall]()
    suite.test[test_dns_cache__test_zero_ttl_always_resolves]()
    suite.test[test_dns_cache__test_distinct_hosts_each_resolve]()
    suite.test[test_dns_cache__test_invalidate_forces_resolve]()
    suite.test[test_dns_cache__test_clear_drops_all]()
    suite.test[test_dns_cache__test_names_match_case_insensitively]()
    suite.test[test_dns_cache__test_cache_is_bounded]()
    suite.test[test_dns_cache__test_int_max_ttl_means_cache_forever]()
    suite.test[
        test_dns_cache__test_ttl_that_overflows_the_expiry_still_caches
    ]()
    suite.test[test_dns_cache__test_saturated_expiries_are_still_evicted]()
    suite^.run()
